# Generated by Django 5.2.1 on 2025-11-05 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('time_limit', models.FloatField(default=1.0)),
                ('memory_limit', models.IntegerField(default=256)),
                ('test_cases_json', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=10)),
                ('code', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('AC', 'AC'), ('WA', 'WA'), ('TLE', 'TLE'), ('RE', 'RE'), ('CE', 'CE')], default='PENDING', max_length=10)),
                ('result', models.JSONField(blank=True, null=True)),
                ('submit_time', models.DateTimeField(auto_now_add=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oj.problem')),
            ],
        ),
    ]
