# Generated by Django 5.2.1 on 2025-11-05 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oj', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='elapsed_time',
            field=models.FloatField(default=-1),
        ),
    ]
