# Generated by Django 5.2.1 on 2025-11-07 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oj', '0002_submission_elapsed_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='test_cases_json',
        ),
        migrations.AddField(
            model_name='problem',
            name='test_cases_file',
            field=models.FileField(blank=True, null=True, upload_to='testcases/'),
        ),
    ]
