# Generated by Django 5.2.1 on 2025-11-08 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oj', '0004_submission_user_submission_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='kpm',
            field=models.FloatField(default=-1),
        ),
    ]
