# Generated by Django 5.2.1 on 2025-11-08 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oj', '0005_submission_kpm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='kpm',
            field=models.FloatField(default=float("nan")),
        ),
    ]
