# Generated by Django 5.2.1 on 2025-11-09 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oj', '0006_alter_submission_kpm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='kpm',
            field=models.FloatField(null=True),
        ),
    ]
