# Generated by Django 5.2.1 on 2026-08-14

import brainrot.models
import brainrot.storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HallOfFameUploadAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accepted', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', '-created_at'], name='hof_attempt_rate_idx')],
            },
        ),
        migrations.CreateModel(
            name='HallOfFameEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField()),
                ('video', models.FileField(storage=brainrot.storage.PrivateMediaStorage(), upload_to=brainrot.models.hall_of_fame_upload_path)),
                ('mime_type', models.CharField(max_length=32)),
                ('duration_seconds', models.FloatField()),
                ('state', models.CharField(choices=[('pending', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hall_of_fame_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-score', 'created_at'),
                'indexes': [
                    models.Index(fields=['state', '-score', 'created_at'], name='hof_public_rank_idx'),
                    models.Index(fields=['user', '-created_at'], name='hof_user_rate_idx'),
                ],
            },
        ),
    ]
