# Generated by Django 5.2.1 on 2026-08-14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brainrot', '0002_halloffameentry_event_timeline'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='halloffameentry',
            name='display_name',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='halloffameentry',
            name='user',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='hall_of_fame_entries',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name='halloffameuploadattempt',
            name='client_key',
            field=models.CharField(default='legacy', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='halloffameuploadattempt',
            name='user',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name='halloffameuploadattempt',
            index=models.Index(
                fields=['client_key', '-created_at'],
                name='hof_attempt_client_idx',
            ),
        ),
    ]
