# Generated by Django 5.2.1 on 2026-08-19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brainrot', '0006_alter_halloffameentry_game_mode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HallOfFameComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=32)),
                ('body', models.TextField()),
                ('client_key', models.CharField(blank=True, max_length=64)),
                ('is_submission_note', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='brainrot.halloffameentry')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hall_of_fame_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created_at', 'id'),
            },
        ),
        migrations.AddIndex(
            model_name='halloffamecomment',
            index=models.Index(fields=['entry', 'created_at'], name='hof_comment_entry_idx'),
        ),
        migrations.AddIndex(
            model_name='halloffamecomment',
            index=models.Index(fields=['user', 'created_at'], name='hof_comment_user_idx'),
        ),
        migrations.AddIndex(
            model_name='halloffamecomment',
            index=models.Index(fields=['client_key', 'created_at'], name='hof_comment_client_idx'),
        ),
    ]
