# Generated by Django 5.2.1 on 2026-08-19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brainrot', '0007_halloffamecomment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HallOfFameReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_key', models.CharField(max_length=32)),
                ('reactor_key', models.CharField(max_length=80)),
                ('emoji', models.CharField(choices=[('😋', '😋'), ('🔥', '🔥'), ('😂', '😂'), ('💀', '💀')], max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='brainrot.halloffamecomment')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='brainrot.halloffameentry')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hall_of_fame_reactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='halloffamereaction',
            constraint=models.UniqueConstraint(fields=('target_key', 'reactor_key', 'emoji'), name='hof_reaction_identity_uniq'),
        ),
        migrations.AddIndex(
            model_name='halloffamereaction',
            index=models.Index(fields=['target_key', 'emoji'], name='hof_reaction_target_idx'),
        ),
        migrations.AddIndex(
            model_name='halloffamereaction',
            index=models.Index(fields=['reactor_key', '-created_at'], name='hof_reaction_reactor_idx'),
        ),
    ]
