# Generated by Django 5.1
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True
    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
    operations = [
        migrations.CreateModel(
            name='AlgorithmicsRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=32)),
                ('session_key', models.CharField(blank=True, max_length=40)),
                ('score', models.PositiveSmallIntegerField(default=0)),
                ('question_ids', models.JSONField(default=list)),
                ('attempts', models.JSONField(default=list)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('is_submitted', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='algorithmics_speedruns', to=settings.AUTH_USER_MODEL)),
            ],
            options={'ordering': ('-score', 'finished_at', 'id')},
        ),
        migrations.AddIndex(model_name='algorithmicsrun', index=models.Index(fields=['-score', 'finished_at'], name='vce_run_score_idx')),
        migrations.AddIndex(model_name='algorithmicsrun', index=models.Index(fields=['token'], name='vce_run_token_idx')),
    ]
